import Head from 'next/head'
import { Card, Group, Heading, Stack, Text } from '@osuresearch/ui'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack as="main" p="xxl">
        <Heading level={1}>Demos</Heading>

        <Group wrap>
          <Card
            headline="New AppShell"
            href="/demos/appshell"
            bgc="light"
          >
            Holy grail layout component for our React apps ready
            to plug&apos;n play.
          </Card>
          <Card
            headline="Marketing - if that's your thing"
            href="/demos/marketing"
            bgc="light"
          >
            Want to do a marketing site that&apos;s all content and no action?
            We got&apos;chu.
          </Card>
          <Card
            headline="Document Your Apps"
            href="/demos/docs"
            bgc="light"
          >
            Want to make a doc site with Next.js and not Docusaurus?
            We got you covered.
          </Card>
          <Card
            headline="Forms! Forms! Forms!"
            href="/demos/ripple"
            bgc="light"
          >
            Can&apos;t get enough making forms? Same.
            Check out our new Ripple framework.
          </Card>

          <Card
            headline="GraphQL-First"
            href="/demos/graphql"
            bgc="light"
          >
            GraphQL-everywhere. Check out the new
            GraphQL Yoga server and GraphiQL editor.
          </Card>

          <Card
            headline="AWS Ready"
            href="/demos/aws"
            bgc="light"
          >
            Going serverless? Us too! Check out some of the
            architecture patterns we're using.
          </Card>
        </Group>
      </Stack>
    </div>
  )
}
